#-------------------------------
# General Site Settings
title: Lily Rudin
# logo: logo.svg # You can add own logo.
description: Masters Student in Computational Analysis and Public Policy at the University of Chicago
#-------------------------------
# Author Settings
author:
  name: Lily Rudin
  image: IMG_3095.jpeg
  say-hello: Masters Student in Computational Analysis and Public Policy at the University of Chicago with 5 Years prior work experience as a data scientist in educational technology. 
  bio: Passionate about using rigorous quantiative analysis to analyze policy outcomes. 


#-------------------------------
# Contact links
linkedin: https://www.linkedin.com/in/lily-rudin-632358162/ # Add your Twitter handle
github: https://github.com/lrudin # Add your Facebook handle
email: lrudin@uchicago.edu # Add your Dribbble handle
phone: 201-546-4922 # Add your Instagram handle



#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
#instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
#instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
